apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    app: new-rhel9-vm
  name: new-rhel9-vm
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/domain: new-rhel9-vm
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: new-rhel9-vm-rootdisk
      volumes:
      - persistentVolumeClaim:
          claimName: new-rhel9-vm-rootdisk
        name: new-rhel9-vm-rootdisk